# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bino_form.ui'
#
# Created: Tue Jan 15 15:04:43 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setEnabled(True)
        Form.resize(600, 489)
        Form.setMouseTracking(True)
        Form.setAcceptDrops(True)
        Form.setAutoFillBackground(False)
        self.Close_Button = QtGui.QPushButton(Form)
        self.Close_Button.setGeometry(QtCore.QRect(320, 450, 75, 23))
        self.Close_Button.setObjectName(_fromUtf8("Close_Button"))
        self.inputfile = QtGui.QLineEdit(Form)
        self.inputfile.setGeometry(QtCore.QRect(102, 20, 161, 20))
        self.inputfile.setObjectName(_fromUtf8("inputfile"))
        self.Run_Button = QtGui.QPushButton(Form)
        self.Run_Button.setGeometry(QtCore.QRect(220, 450, 75, 23))
        self.Run_Button.setObjectName(_fromUtf8("Run_Button"))
        self.ciclos = QtGui.QLineEdit(Form)
        self.ciclos.setGeometry(QtCore.QRect(103, 50, 61, 20))
        self.ciclos.setObjectName(_fromUtf8("ciclos"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Mutualism_checkbox = QtGui.QCheckBox(Form)
        self.Mutualism_checkbox.setGeometry(QtCore.QRect(30, 112, 131, 17))
        self.Mutualism_checkbox.setObjectName(_fromUtf8("Mutualism_checkbox"))
        self.foodweb_checkbox = QtGui.QCheckBox(Form)
        self.foodweb_checkbox.setEnabled(False)
        self.foodweb_checkbox.setGeometry(QtCore.QRect(182, 113, 91, 17))
        self.foodweb_checkbox.setObjectName(_fromUtf8("foodweb_checkbox"))
        self.pl_ext_period = QtGui.QLineEdit(Form)
        self.pl_ext_period.setGeometry(QtCore.QRect(60, 290, 21, 20))
        self.pl_ext_period.setDragEnabled(True)
        self.pl_ext_period.setObjectName(_fromUtf8("pl_ext_period"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 290, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pl_ext_spike = QtGui.QLineEdit(Form)
        self.pl_ext_spike.setGeometry(QtCore.QRect(120, 290, 31, 20))
        self.pl_ext_spike.setDragEnabled(True)
        self.pl_ext_spike.setObjectName(_fromUtf8("pl_ext_spike"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(90, 290, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(160, 290, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pl_ext_numperiod = QtGui.QLineEdit(Form)
        self.pl_ext_numperiod.setGeometry(QtCore.QRect(200, 290, 31, 20))
        self.pl_ext_numperiod.setDragEnabled(True)
        self.pl_ext_numperiod.setObjectName(_fromUtf8("pl_ext_numperiod"))
        self.pl_ext_rate = QtGui.QLineEdit(Form)
        self.pl_ext_rate.setGeometry(QtCore.QRect(280, 290, 41, 20))
        self.pl_ext_rate.setDragEnabled(True)
        self.pl_ext_rate.setObjectName(_fromUtf8("pl_ext_rate"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(250, 290, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pl_ext_start = QtGui.QLineEdit(Form)
        self.pl_ext_start.setGeometry(QtCore.QRect(360, 290, 31, 20))
        self.pl_ext_start.setDragEnabled(True)
        self.pl_ext_start.setObjectName(_fromUtf8("pl_ext_start"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(330, 290, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pl_ext_species = QtGui.QLineEdit(Form)
        self.pl_ext_species.setGeometry(QtCore.QRect(440, 290, 61, 20))
        self.pl_ext_species.setDragEnabled(True)
        self.pl_ext_species.setObjectName(_fromUtf8("pl_ext_species"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(400, 290, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pol_ext_period = QtGui.QLineEdit(Form)
        self.pol_ext_period.setGeometry(QtCore.QRect(60, 370, 21, 20))
        self.pol_ext_period.setDragEnabled(True)
        self.pol_ext_period.setObjectName(_fromUtf8("pol_ext_period"))
        self.pol_ext_numperiod = QtGui.QLineEdit(Form)
        self.pol_ext_numperiod.setGeometry(QtCore.QRect(200, 370, 31, 20))
        self.pol_ext_numperiod.setDragEnabled(True)
        self.pol_ext_numperiod.setObjectName(_fromUtf8("pol_ext_numperiod"))
        self.pol_ext_start = QtGui.QLineEdit(Form)
        self.pol_ext_start.setGeometry(QtCore.QRect(360, 370, 31, 20))
        self.pol_ext_start.setObjectName(_fromUtf8("pol_ext_start"))
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(330, 370, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(160, 370, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pol_ext_rate = QtGui.QLineEdit(Form)
        self.pol_ext_rate.setGeometry(QtCore.QRect(280, 370, 41, 20))
        self.pol_ext_rate.setDragEnabled(True)
        self.pol_ext_rate.setObjectName(_fromUtf8("pol_ext_rate"))
        self.pol_ext_species = QtGui.QLineEdit(Form)
        self.pol_ext_species.setGeometry(QtCore.QRect(440, 370, 61, 20))
        self.pol_ext_species.setDragEnabled(True)
        self.pol_ext_species.setObjectName(_fromUtf8("pol_ext_species"))
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(90, 370, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(250, 370, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(400, 370, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(30, 370, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.pol_ext_spike = QtGui.QLineEdit(Form)
        self.pol_ext_spike.setGeometry(QtCore.QRect(120, 370, 31, 20))
        self.pol_ext_spike.setDragEnabled(True)
        self.pol_ext_spike.setObjectName(_fromUtf8("pol_ext_spike"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(30, 260, 111, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(30, 340, 171, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.ClearPlants = QtGui.QPushButton(Form)
        self.ClearPlants.setGeometry(QtCore.QRect(510, 290, 61, 21))
        self.ClearPlants.setObjectName(_fromUtf8("ClearPlants"))
        self.ClearPolin = QtGui.QPushButton(Form)
        self.ClearPolin.setGeometry(QtCore.QRect(510, 370, 61, 21))
        self.ClearPolin.setObjectName(_fromUtf8("ClearPolin"))
        self.output_suffix = QtGui.QLineEdit(Form)
        self.output_suffix.setGeometry(QtCore.QRect(442, 20, 131, 20))
        self.output_suffix.setObjectName(_fromUtf8("output_suffix"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(375, 85, 201, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.Comments_text = QtGui.QPlainTextEdit(Form)
        self.Comments_text.setGeometry(QtCore.QRect(300, 101, 271, 121))
        self.Comments_text.setObjectName(_fromUtf8("Comments_text"))
        self.label_report = QtGui.QLabel(Form)
        self.label_report.setGeometry(QtCore.QRect(210, 410, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_report.setFont(font)
        self.label_report.setText(_fromUtf8(""))
        self.label_report.setObjectName(_fromUtf8("label_report"))
        self.URL_report = QtGui.QLabel(Form)
        self.URL_report.setGeometry(QtCore.QRect(270, 400, 311, 40))
        self.URL_report.setText(_fromUtf8(""))
        self.URL_report.setOpenExternalLinks(True)
        self.URL_report.setObjectName(_fromUtf8("URL_report"))
        self.save_output_checkbox = QtGui.QCheckBox(Form)
        self.save_output_checkbox.setGeometry(QtCore.QRect(182, 131, 131, 17))
        self.save_output_checkbox.setObjectName(_fromUtf8("save_output_checkbox"))
        self.label_19 = QtGui.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(30, 230, 161, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.random_removal = QtGui.QLineEdit(Form)
        self.random_removal.setGeometry(QtCore.QRect(170, 230, 31, 20))
        self.random_removal.setDragEnabled(True)
        self.random_removal.setObjectName(_fromUtf8("random_removal"))
        self.select_input_file = QtGui.QPushButton(Form)
        self.select_input_file.setGeometry(QtCore.QRect(30, 20, 60, 21))
        self.select_input_file.setObjectName(_fromUtf8("select_input_file"))
        self.May_checkbox = QtGui.QCheckBox(Form)
        self.May_checkbox.setGeometry(QtCore.QRect(30, 132, 131, 17))
        self.May_checkbox.setObjectName(_fromUtf8("May_checkbox"))
        self.Bastolla_checkbox = QtGui.QCheckBox(Form)
        self.Bastolla_checkbox.setGeometry(QtCore.QRect(30, 151, 131, 17))
        self.Bastolla_checkbox.setObjectName(_fromUtf8("Bastolla_checkbox"))
        self.label_20 = QtGui.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(30, 90, 201, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_2.setBuddy(self.label_2)
        self.label_4.setBuddy(self.inputfile)
        self.label_5.setBuddy(self.inputfile)
        self.label_6.setBuddy(self.inputfile)
        self.label_7.setBuddy(self.inputfile)
        self.label_8.setBuddy(self.inputfile)
        self.label_9.setBuddy(self.inputfile)
        self.label_10.setBuddy(self.inputfile)
        self.label_11.setBuddy(self.inputfile)
        self.label_13.setBuddy(self.inputfile)
        self.label_14.setBuddy(self.inputfile)
        self.label_15.setBuddy(self.inputfile)
        self.label_16.setBuddy(self.inputfile)
        self.label_12.setBuddy(self.inputfile)
        self.label_17.setBuddy(self.inputfile)
        self.label_3.setBuddy(self.inputfile)
        self.label_18.setBuddy(self.inputfile)
        self.label_report.setBuddy(self.inputfile)
        self.label_19.setBuddy(self.inputfile)
        self.label_20.setBuddy(self.inputfile)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.Close_Button, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QObject.connect(self.Run_Button, QtCore.SIGNAL(_fromUtf8("clicked()")), self.ciclos.update)
        QtCore.QObject.connect(self.Run_Button, QtCore.SIGNAL(_fromUtf8("clicked()")), self.Mutualism_checkbox.update)
        QtCore.QObject.connect(self.Run_Button, QtCore.SIGNAL(_fromUtf8("clicked()")), self.foodweb_checkbox.update)
        QtCore.QObject.connect(self.ClearPlants, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pl_ext_species.clear)
        QtCore.QObject.connect(self.ClearPlants, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pl_ext_rate.clear)
        QtCore.QObject.connect(self.ClearPlants, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pl_ext_numperiod.clear)
        QtCore.QObject.connect(self.ClearPlants, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pl_ext_spike.clear)
        QtCore.QObject.connect(self.ClearPlants, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pl_ext_period.clear)
        QtCore.QObject.connect(self.ClearPlants, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pl_ext_start.clear)
        QtCore.QObject.connect(self.ClearPolin, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pol_ext_species.clear)
        QtCore.QObject.connect(self.ClearPolin, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pol_ext_start.clear)
        QtCore.QObject.connect(self.ClearPolin, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pol_ext_rate.clear)
        QtCore.QObject.connect(self.ClearPolin, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pol_ext_numperiod.clear)
        QtCore.QObject.connect(self.ClearPolin, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pol_ext_spike.clear)
        QtCore.QObject.connect(self.ClearPolin, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pol_ext_period.clear)
        QtCore.QObject.connect(self.Run_Button, QtCore.SIGNAL(_fromUtf8("clicked()")), self.URL_report.repaint)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.Close_Button.setText(QtGui.QApplication.translate("Form", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.Run_Button.setText(QtGui.QApplication.translate("Form", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Days", None, QtGui.QApplication.UnicodeUTF8))
        self.Mutualism_checkbox.setText(QtGui.QApplication.translate("Form", "Logistic Approach", None, QtGui.QApplication.UnicodeUTF8))
        self.foodweb_checkbox.setText(QtGui.QApplication.translate("Form", "Foodweb", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Years", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Spike", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Species", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Spike", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Species", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Years", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Plants extinctions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Pollinators extinctions", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearPlants.setText(QtGui.QApplication.translate("Form", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearPolin.setText(QtGui.QApplication.translate("Form", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Output suffix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Comments for report", None, QtGui.QApplication.UnicodeUTF8))
        self.save_output_checkbox.setText(QtGui.QApplication.translate("Form", "Save output data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Random links removal", None, QtGui.QApplication.UnicodeUTF8))
        self.select_input_file.setText(QtGui.QApplication.translate("Form", "Input file", None, QtGui.QApplication.UnicodeUTF8))
        self.May_checkbox.setText(QtGui.QApplication.translate("Form", "May", None, QtGui.QApplication.UnicodeUTF8))
        self.Bastolla_checkbox.setText(QtGui.QApplication.translate("Form", "Bastolla", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Mutualism Model", None, QtGui.QApplication.UnicodeUTF8))

