global DAYS_YEAR
global ldevices_info, lfich_info
global LINES_INFO_MATRIX
global INPUTFILES_PATH, OUTPUTILES_PATH, SIMFILES_PATH
global MIN_COLLAPSE_YEARS, IGNORE_INIT_COLLAPSE
global TOL_EXTINCTION

DAYS_YEAR = 365
LINES_INFO_MATRIX = 5
MIN_COLLAPSE_YEARS = 8
FACT_COLLAPSE_SIN = 2
IGNORE_INIT_COLLAPSE = 0.2
TOL_EXTINCTION = -0.001
INPUTFILES_PATH = 'input/'
OUTPUTILES_PATH = 'output/'
SIMFILES_PATH = 'simfiles/'
OUTPUTDATA_PREFIX = 'output_data_'
IGNORE_REFF = 0.000001

if __name__ == '__main__':
    pass